# Generated by Django 4.2.4 on 2023-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                default="post-number", help_text="Enter the title", max_length=50
            ),
        ),
    ]
