# Generated by Django 4.2.4 on 2023-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
